name: dbt_spcs
version: 1.0.0
config-version: 2
profile: snowflake_dbt

model-paths: ["models"]
macro-paths: ["macros"]

models:
  dbt_spcs:
    +materialized: view         # default
    greet_now:
      +materialized: incremental
      +unique_key: run_date
      +on_schema_change: sync_all_columns
